### ISSUE TITLE
VS Code Suggestion Window 

### ISSUE THREAD

**Issue by travispamaral** [minamarkham/yonce#6]
Hi Mina!

Im in love with this theme, I have it on all the things! 😄Do you have any plans to add a highlight style to this Quick Suggestion window in VS Code? I find it is sometimes hard to see what you are selecting if you navigate it with arrows. Thought I would at least ask :)

Thanks so much for this theme and your work on it! I recommend it to everyone!

![](https://cl.ly/afc91a317925/Image%202018-11-15%20at%208.24.48%20AM.png)

**Comment by ifahrentholz** [comment]
I've tried to overwrite the styles via "workbench.colorCustomizations" but it did not work.
```
"workbench.colorCustomizations": {
    "[Yoncé]": {
      "list.focusBackground": "#919CB915",
      "list.focusForeground": "#F6F0FFEA",
    }
  },
``` 
I have no clue what's the problem :(

**Comment by jeffrafter** [comment]
@ifahrentholz I think you want: 

```
  "workbench.colorCustomizations": {
    "editorSuggestWidget.selectedBackground": "#FC43847A"
  },
```

**Comment by ifahrentholz** [comment]
Nice - that works ! 
Thanks @jeffrafter
